spring.application.name=shuttle_mate

# 서버 실행 포트 지정
server.port=${PORT:8080}

# DB 드라이버 지정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# DB 연결 주소 및 DB 계정 정보
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# MyBatis 설정
# xml 매퍼 파일 위치 (src/main/resources/sqlmap/mapper/*.xml)
mybatis.mapper-locations=classpath:sqlmap/mapper/**/*.xml

# 문자 인코딩 설정
spring.messages.encoding=UTF-8

# View 파일 위치 지정
spring.mvc.view.prefix=/WEB-INF/

# View 파일 확장자 지정
spring.mvc.view.suffix=.jsp
