spring.application.name=shuttle_mate
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.messages.encoding=UTF-8

spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
